name: "Test - action"

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  typecheck:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Build
        run: yarn build

  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Use Node.js LTS
        uses: actions/setup-node@v4
        with:
          node-version: "20.x"
          cache: "yarn"
      - name: Install dependencies
        run: yarn
      - name: Test
        run: yarn test
